server:
  port: 80

spring:
  application:
    name: cloud-consumer-feign-order
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: feign-order80  #显示实例名称
    prefer-ip-address: true   #访问路径就可以显示ip

#设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000

logging:
  level:
    # feign日志以什么级别监控哪个接口（以debug的形式，打印full的全日志）
    com.atguigu.springcloud.service.PaymentFeignService: debug
